const jCategory = [
    {
        index : 0,
        image : "../images/google.png",
        title : "Web Developer",
        rate : "$1000-1300/m",
        av : "-  Full Time",
        companyName : "Google",
        location : "USA",
        vacancy : "01",
        hours : "50h / Week",
        description : "Google is seeking a passionate, innovative, and skilled Web Developer to join our growing team of world-class technologists, designers, and engineers. In this role, you will design, build, and maintain high-performance, scalable, and visually appealing web applications that enhance the experiences of millions of users worldwide. You will collaborate closely with UX designers, product managers, and backend developers to deliver cutting-edge web solutions aligned with Google's mission to organize the world's information and make it universally accessible and useful.",
        workPlace : "-  Hybrid",
        qualification : "-  Bachelor’s degree in Computer Science, Web Development, or a related technical field, or equivalent practical experience",
        experience : "-  3+ years of professional experience in front-end or full-stack web development.",
    },

    {
        index : 1,
        image : "../images/uber.png",
        title : "Software Engineer",
        rate : "$900-1200/m",
        av : "-  Freelancer",
        companyName : "Uber",
        location : "INDIA",
        vacancy : "15",
        hours : "40h / Week",
        description : "Uber is looking for a highly skilled and motivated Freelance Software Engineer to join its remote engineering network. This is an exciting opportunity to work on impactful projects, build scalable applications, and collaborate with some of the brightest minds in the industry. As a freelance engineer, you will have the flexibility to work from anywhere while contributing to Uber’s mission of shaping the future of mobility.",
        workPlace : "-  Work From Home",
        qualification : "-  Bachelor’s degree in Computer Science, Software Engineering, or a related technical field, or equivalent professional experience.",
        experience : "-  2+ years of hands-on software development experience.",
    },

    {
        index : 2,
        image : "../images/linkedin.png",
        title : "Business Associate",
        rate : "$800-1000/m",
        av : "-  Part Time",
        companyName : "Linkedin",
        location : "Dubai",
        vacancy : "11",
        hours : "39h / Week",
        description : "LinkedIn is seeking a dynamic and results-driven Business Associate to join its team. This role is ideal for an analytical, strategic thinker with a strong business acumen and a passion for professional networking, technology, and business growth. As a Business Associate, you will support key business initiatives, analyze market data, collaborate across teams, and contribute to strategic decision-making processes that drive LinkedIn’s global impact.",
        workPlace : "-  Office",
        qualification : "-  Bachelor’s degree in Business Administration, Economics, Marketing, or a related field.",
        experience : "-  2+ years of relevant experience in business analysis, consulting, project management, or business operations.",
    },

    {
        index : 3,
        image : "../images/facebook.png",
        title : "Digital Marketing",
        rate : "$1100-1400/m",
        av : "-  Freelancer",
        companyName : "Facebook",
        location : "Banglore",
        vacancy : "05",
        hours : "40h / Week",
        description : "Facebook (Meta) is seeking an innovative and results-oriented Digital Marketing Specialist to join its marketing team. This is an exciting opportunity to develop and execute data-driven digital marketing campaigns that drive engagement, user growth, brand awareness, and conversion across Facebook’s platforms. You’ll work closely with cross-functional teams to deliver impactful marketing strategies that resonate with diverse global audiences",
        workPlace : "-  Hybrid",
        qualification : "-  Bachelor’s degree in Marketing, Communications, Business, or a related field.",
        experience : "-  2+ years of experience in digital marketing, social media advertising, or performance marketing.",
    },

    {
        index : 4,
        image : "../images/yahoo.png",
        title : "User Experience",
        rate : "$800-1000/m",
        av : "-  Part Time",
        companyName : "Yahoo",
        location : "Gurugram",
        vacancy : "08",
        hours : "50h / Week",
        description : "Yahoo is seeking a creative, detail-oriented, and user-focused User Experience (UX) Designer to join its growing product design team. In this role, you will play a pivotal part in shaping intuitive, engaging, and accessible digital experiences across Yahoo’s suite of products and services. You’ll collaborate with multidisciplinary teams to translate user needs and business goals into seamless, visually compelling digital experiences that enhance user satisfaction and loyalty.",
        workPlace : "-  Office",
        qualification : "-  Bachelor’s degree in User Experience Design, Human-Computer Interaction, Graphic Design, or a related field.",
        experience : "-  1+ years of professional experience in UX design, interaction design, or product design.",
    },

    {
        index : 5,
        image : "../images/apple.png",
        title : "ios Developer",
        rate : "$1500-1800/m",
        av : "-  Full Time",
        companyName : "Apple",
        location : "California",
        vacancy : "02",
        hours : "25h / Week",
        description : "Apple is seeking a talented and passionate iOS Developer to join its world-class mobile development team. In this role, you will be responsible for building, optimizing, and maintaining high-performance, user-friendly iOS applications that reach millions of customers worldwide. This is a unique opportunity to work on innovative projects in a collaborative, fast-paced environment, contributing directly to Apple’s mobile ecosystem.",
        workPlace : "-  Hybrid",
        qualification : "-  Bachelor’s degree in Computer Science, Software Engineering, or a related field.",
        experience : "-  2+ years of professional iOS development experience.",
    },

    {
        index : 6,
        image : "../images/amazon.png",
        title : "Data Analyst",
        rate : "$1100-1400/m",
        av : "-  Full Time",
        companyName : "Amazon",
        location : "Japan",
        vacancy : "18",
        hours : "30h / Week",
        description : "Amazon is seeking an analytical, detail-oriented, and data-driven Data Analyst to join its growing analytics team. In this role, you will work closely with business leaders, product teams, and technical experts to gather insights, optimize operations, and drive data-informed decision-making. You’ll play a key role in analyzing large datasets, uncovering trends, and providing actionable recommendations that support Amazon’s operational, marketing, and business goals.",
        workPlace : "-  Office",
        qualification : "-  Bachelor’s degree in Data Analytics, Computer Science, Statistics, Economics, Business, or a related field.",
        experience : "-  3+ years of professional experience in a data analyst or business analyst role.",
    },

    {
        index : 7,
        image : "../images/accenture.png",
        title : "Business Analyst",
        rate : "$1300-1500/m",
        av : "-  Part Time",
        companyName : "Accenture",
        location : "Pune",
        vacancy : "20",
        hours : "46h / Week",
        description : "Accenture is looking for a highly motivated and detail-oriented Business Analyst to join its consulting and strategy team. This role involves working closely with clients, project managers, and technical teams to gather, analyze, and translate business requirements into innovative solutions. The ideal candidate will have strong analytical abilities, excellent communication skills, and a passion for solving complex business problems through data-driven decision-making.",
        workPlace : "-  Hybrid",
        qualification : "-  Bachelor’s degree in Business Administration, Economics, Information Systems, or a related field.",
        experience : "-  2+ years of experience as a Business Analyst or in a similar consulting/analytics role.",
    },


];